### ISSUE TITLE
Take Sensitive Information from Secrets

### ISSUE THREAD

**Issue by usamaahmadkhan** [stakater/ProxyInjector#26]
Right now ProxyInjector uses Client-secret directly as a string. It would  be a better and secure approach if it takes this sensitive information from Secrets

**Comment by lukasmrtvy** [comment]
+1 
Its no possible to use GitOps, cuz of client-secret annotation in plaintext

**Comment by usamaahmadkhan** [comment]
@lukasmrtvy v0.0.22 now supports existing secrets. This will now fulfill GitOps use case
